# Generated by Django 4.1 on 2022-11-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=7)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.CharField(max_length=2)),
                ('estado', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
    ]
