# Generated by Django 4.1 on 2022-11-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_APP', '0002_alter_reserva_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Reservado'], [1, 'Completado'], [2, 'Anulado'], [3, 'No Asistens']]),
        ),
    ]
